# Generated by Django 5.1.3 on 2025-01-23 09:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompactSettlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LakeOrPond',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MeadowOrPasture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultiOtherType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326, verbose_name='Geometry')),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
