# Generated by Django 5.1.3 on 2025-02-10 22:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0002_highwayfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakeorpond',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry'),
        ),
    ]
