# Generated by Django 5.1.3 on 2025-02-10 22:58

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoportal', '0003_alter_lakeorpond_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compactsettlement',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Geometry'),
        ),
    ]
